"""The native platforms: a cover is a cover, and a jammed lock says so.

Every fixture in `fixtures/entity_change_{cover,lock,climate,alarm,vacuum}.json`
was generated by running the hub's OWN `entity-catalog.ts` with the native
platform set negotiated. Nothing in them was typed by hand, so a control
name or a topic this integration gets wrong here gets it wrong against the
hub too — which is the whole reason the wire format is asserted through
recordings rather than through a shape invented to match this code.
"""

from __future__ import annotations

import copy
from typing import Any
from unittest.mock import AsyncMock

from homeassistant.components import persistent_notification as pn
from homeassistant.components.climate import ClimateEntityFeature, HVACMode
from homeassistant.components.cover import CoverEntityFeature
from homeassistant.components.lock import LockEntityFeature
from homeassistant.components.vacuum import VacuumEntityFeature
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.camstack.const import COMMAND_ROUTE_PATH

from .conftest import (
    HEARTBEAT,
    load_fixture,
    push,
    setup_integration,
)

ENTITY_CHANGE_COVER: dict[str, Any] = load_fixture("entity_change_cover.json")
ENTITY_CHANGE_COVER_LEGACY: dict[str, Any] = load_fixture(
    "entity_change_cover_legacy.json"
)
ENTITY_CHANGE_LOCK: dict[str, Any] = load_fixture("entity_change_lock.json")
ENTITY_CHANGE_CLIMATE: dict[str, Any] = load_fixture("entity_change_climate.json")
ENTITY_CHANGE_ALARM: dict[str, Any] = load_fixture("entity_change_alarm.json")
ENTITY_CHANGE_VACUUM: dict[str, Any] = load_fixture("entity_change_vacuum.json")

COVER = "cover.tapparella_salone_cover"
LOCK = "lock.porta_ingresso_lock_control"
CLIMATE = "climate.termostato_salone_climate_control"
ALARM = "alarm_control_panel.allarme_casa_alarm_panel"
VACUUM = "vacuum.robot_vacuum_control"


def _notifications(hass: HomeAssistant) -> dict[str, Any]:
    """Return the persistent notifications, which are not entities."""
    return hass.data.get(pn.DOMAIN, {})


def topic(message: dict[str, Any], entity: str) -> str:
    """Return the state topic the hub builds for one entity of a device."""
    return f"camstack/{message['device_id']}/{entity}"


def state_update(topic_name: str, value: str) -> dict[str, Any]:
    """Return one state update as the hub sends it — the value is a STRING."""
    return {"type": "state_update", "topic": topic_name, "value": value}


async def announce(
    hass: HomeAssistant, entry: MockConfigEntry, message: dict[str, Any]
) -> None:
    """Deliver one device and bring the link up."""
    await push(hass, entry, message)
    await push(hass, entry, HEARTBEAT)


# --- cover -----------------------------------------------------------------


async def test_a_cover_arrives_as_one_cover_and_not_as_five_entities(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The whole point of the native half.

    The same shutter through the older platforms is a state `sensor`, two
    `number`s and three `button`s: automatable, and not a cover.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER)

    assert hass.states.get(COVER) is not None
    assert hass.states.get("sensor.tapparella_salone_cover") is None
    assert hass.states.get("number.tapparella_salone_position") is None
    assert hass.states.get("button.tapparella_salone_open") is None


async def test_a_cover_advertises_exactly_what_the_hub_routed(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """A feature is a service call, and a service call needs a route.

    The fixture's hub routes position, tilt and the three verbs, so all
    six features are offered. A hub that routed none would produce a cover
    that reports and does not pretend to move.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER)

    features = hass.states.get(COVER).attributes["supported_features"]
    assert features & CoverEntityFeature.OPEN
    assert features & CoverEntityFeature.CLOSE
    assert features & CoverEntityFeature.STOP
    assert features & CoverEntityFeature.SET_POSITION
    assert features & CoverEntityFeature.SET_TILT_POSITION


async def test_a_cover_with_no_routes_reports_and_offers_nothing(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """D62 generalised: a prettier platform is not a reason to lie.

    A hub whose route table cannot move a cover sends the controls with no
    command topic — the reading is still worth having — and the entity must
    then advertise no way to move it.
    """
    message = copy.deepcopy(ENTITY_CHANGE_COVER)
    component = message["cmps"]["cover-cover"]
    for control in component["controls"].values():
        control.pop("command_topic", None)
    component["controls"] = {
        name: control
        for name, control in component["controls"].items()
        if "state_topic" in control
    }
    component.pop("command_topic", None)

    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, message)

    assert hass.states.get(COVER).attributes["supported_features"] == 0


async def test_a_cover_reads_its_position_from_the_topic_it_always_used(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The native half changes STRUCTURE and never the value plane.

    `cover_position` is the topic the degraded `number` published on, and
    the projector on the hub is untouched — which is what makes the two
    halves unable to disagree.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER)
    await push(
        hass, config_entry, state_update(topic(ENTITY_CHANGE_COVER, "cover"), "open")
    )
    await push(
        hass,
        config_entry,
        state_update(topic(ENTITY_CHANGE_COVER, "cover_position"), "40"),
    )

    state = hass.states.get(COVER)
    assert state.attributes["current_position"] == 40
    assert state.state == "open"


async def test_a_stopped_cover_is_judged_by_its_position_not_its_state(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`stopped` says nothing about WHERE it stopped.

    Answering "is it closed" from the lifecycle alone calls a half-open
    blind open, and every "close the blinds if they are not already"
    automation skips it.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER)
    await push(
        hass, config_entry, state_update(topic(ENTITY_CHANGE_COVER, "cover"), "stopped")
    )
    await push(
        hass,
        config_entry,
        state_update(topic(ENTITY_CHANGE_COVER, "cover_position"), "0"),
    )

    assert hass.states.get(COVER).state == "closed"


async def test_opening_a_cover_presses_the_verb_the_hub_declared(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The service becomes the hub's own `{topic, value}`, and no new one."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER)

    await hass.services.async_call(
        "cover", "open_cover", {"entity_id": COVER}, blocking=True
    )

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {"topic": topic(ENTITY_CHANGE_COVER, "cover_open") + "/set", "value": "PRESS"},
    )


async def test_setting_a_position_writes_the_number_the_hub_routes(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The position control is the entity the route table already resolves."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER)

    await hass.services.async_call(
        "cover",
        "set_cover_position",
        {"entity_id": COVER, "position": 35},
        blocking=True,
    )

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {"topic": topic(ENTITY_CHANGE_COVER, "cover_position") + "/set", "value": "35"},
    )


async def test_a_verb_is_never_optimistic(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Pressing `open` does not make a shutter open — it starts it moving.

    Writing `open` into the state here would show it open while it is still
    travelling, and every automation waiting on it would fire early.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER)
    await push(
        hass, config_entry, state_update(topic(ENTITY_CHANGE_COVER, "cover"), "closed")
    )

    await hass.services.async_call(
        "cover", "open_cover", {"entity_id": COVER}, blocking=True
    )

    assert hass.states.get(COVER).state == "closed"


# --- lock ------------------------------------------------------------------


async def test_a_jammed_lock_is_not_an_unlocked_one(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The reason the lock platform is worth having.

    Through a `switch` this state reports as "off", which is the answer that
    makes an "is everything secure" automation say yes.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_LOCK)
    await push(
        hass,
        config_entry,
        state_update(topic(ENTITY_CHANGE_LOCK, "lock_control_state"), "jammed"),
    )

    assert hass.states.get(LOCK).state == "jammed"


async def test_a_lock_reads_the_enum_and_writes_the_switch(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Two topics, because the degraded lock published a DERIVED boolean.

    Reading the primary would throw away exactly the distinction the
    platform exists for; writing the extra would reach no route.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_LOCK)
    await push(
        hass,
        config_entry,
        state_update(topic(ENTITY_CHANGE_LOCK, "lock_control_state"), "locked"),
    )
    assert hass.states.get(LOCK).state == "locked"

    await hass.services.async_call("lock", "unlock", {"entity_id": LOCK}, blocking=True)

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(ENTITY_CHANGE_LOCK, "lock_control") + "/set",
            "value": "unlock",
        },
    )
    # Accepted, not done: the bolt has not moved and the hub says when it has.
    assert hass.states.get(LOCK).state == "unlocking"


async def test_a_lock_without_a_latch_route_offers_no_open(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`lock.open` is a service; without a route it must not be advertised."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_LOCK)

    features = hass.states.get(LOCK).attributes["supported_features"]
    assert not features & LockEntityFeature.OPEN


# --- climate ---------------------------------------------------------------


async def test_a_thermostat_offers_the_modes_its_own_device_reported(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The vocabulary is per device, and it is the reason it can be native.

    A static list would offer an operator modes their unit rejects while
    hiding the ones it takes — which is why the degraded half refuses to
    make this a `select` at all.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_CLIMATE)

    assert hass.states.get(CLIMATE).attributes["hvac_modes"] == [
        HVACMode.OFF,
        HVACMode.HEAT,
        HVACMode.AUTO,
    ]


async def test_a_thermostat_reports_the_setpoint_and_what_it_measures(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """One entity, five values, and the card that draws them."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_CLIMATE)
    for entity, value in (
        ("climate_control", "heat"),
        ("climate_control_target", "21.5"),
        ("climate_control_current_temp", "19.5"),
        ("climate_control_current_humidity", "44"),
    ):
        await push(
            hass,
            config_entry,
            state_update(topic(ENTITY_CHANGE_CLIMATE, entity), value),
        )

    state = hass.states.get(CLIMATE)
    assert state.state == HVACMode.HEAT
    assert state.attributes["temperature"] == 21.5
    assert state.attributes["current_temperature"] == 19.5
    assert state.attributes["current_humidity"] == 44


async def test_a_thermostat_sends_the_setpoint_the_operator_moved(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """A single-setpoint call carries `temperature` and nothing else."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_CLIMATE)

    await hass.services.async_call(
        "climate",
        "set_temperature",
        {"entity_id": CLIMATE, "temperature": 20.5},
        blocking=True,
    )

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(ENTITY_CHANGE_CLIMATE, "climate_control_target") + "/set",
            "value": "20.5",
        },
    )


async def test_a_thermostat_turns_off_through_its_own_mode_vocabulary(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`climate.turn_off` is what a voice assistant calls."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_CLIMATE)
    assert (
        hass.states.get(CLIMATE).attributes["supported_features"]
        & ClimateEntityFeature.TURN_OFF
    )

    await hass.services.async_call(
        "climate", "turn_off", {"entity_id": CLIMATE}, blocking=True
    )

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(ENTITY_CHANGE_CLIMATE, "climate_control") + "/set",
            "value": "off",
        },
    )


async def test_a_control_the_native_entity_cannot_express_stays_beside_it(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Nothing is silently lost by gaining a platform.

    Vertical swing is a boolean and Home Assistant's climate expresses
    swing as a mode vocabulary the capability does not have, so the hub
    leaves it as its own `switch` rather than absorbing it into a control
    that could not drive it.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_CLIMATE)

    registry = er.async_get(hass)
    assert (
        registry.async_get_entity_id(
            "switch", "camstack", "camstack_tado:BU123_climate_control_swing_vertical"
        )
        is not None
    )


# --- alarm panel -----------------------------------------------------------


async def test_an_alarm_panel_finally_produces_an_entity(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """This platform closes a hole rather than improving a projection.

    The hub has announced `alarm_control_panel` since the native export
    shipped and no released version of this integration built it, so every
    exported panel produced a warning line and no entity at all.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_ALARM)
    await push(
        hass,
        config_entry,
        state_update(topic(ENTITY_CHANGE_ALARM, "alarm_panel"), "armed_away"),
    )

    assert hass.states.get(ALARM).state == "armed_away"


async def test_an_alarm_panel_offers_only_the_modes_it_accepts(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """A panel that cannot arm `vacation` must not show the button."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_ALARM)

    features = hass.states.get(ALARM).attributes["supported_features"]
    assert features & 1  # ARM_HOME
    assert features & 2  # ARM_AWAY
    assert features & 4  # ARM_NIGHT
    assert not features & 32  # ARM_VACATION, which this panel did not declare


async def test_arming_speaks_the_vocabulary_the_hub_already_parses(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`ARM_AWAY` is one of the three spellings `parseAlarmAction` accepts."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_ALARM)

    await hass.services.async_call(
        "alarm_control_panel", "alarm_arm_away", {"entity_id": ALARM}, blocking=True
    )

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(ENTITY_CHANGE_ALARM, "alarm_panel") + "/set",
            "value": "ARM_AWAY",
        },
    )


async def test_a_refused_arm_never_shows_as_armed(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The hub refuses an arm the panel turns down — an open contact.

    Showing `armed_away` over that refusal would leave Home Assistant
    reporting a secured house with an open door.
    """
    from custom_components.camstack.api import CamStackError

    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_ALARM)
    await push(
        hass,
        config_entry,
        state_update(topic(ENTITY_CHANGE_ALARM, "alarm_panel"), "disarmed"),
    )
    mock_client.async_post_addon_route = AsyncMock(
        side_effect=CamStackError("a contact this mode covers is open")
    )

    with_error = False
    try:
        await hass.services.async_call(
            "alarm_control_panel", "alarm_arm_away", {"entity_id": ALARM}, blocking=True
        )
    except Exception:
        with_error = True

    assert with_error
    assert hass.states.get(ALARM).state == "disarmed"


# --- vacuum ----------------------------------------------------------------


async def test_a_vacuum_keeps_the_sensors_its_platform_cannot_show(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The sensors Home Assistant's vacuum has nowhere to show.

    It deprecated the battery attribute and never had a place for a
    progress percentage or a vendor error string.

    They stay their own sensors, so the operator does not lose them by
    gaining a vacuum.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_VACUUM)

    assert hass.states.get(VACUUM) is not None
    registry = er.async_get(hass)
    for unique_id in (
        "camstack_roborock:s7_vacuum_control_battery",
        "camstack_roborock:s7_vacuum_control_progress",
    ):
        assert registry.async_get_entity_id("sensor", "camstack", unique_id) is not None


async def test_a_drying_dock_still_reads_as_working(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`drying` is the one camstack state Home Assistant has no word for.

    Folding it into `cleaning` beats dropping the update: an unmapped state
    would leave the entity on its LAST one for the whole dry cycle, which
    is the reading an automation would act on.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_VACUUM)
    await push(
        hass,
        config_entry,
        state_update(topic(ENTITY_CHANGE_VACUUM, "vacuum_control"), "drying"),
    )

    assert hass.states.get(VACUUM).state == "cleaning"


async def test_a_vacuum_advertises_the_verbs_the_hub_routed(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Five verbs, one suction control — all declared, none assumed."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_VACUUM)

    features = hass.states.get(VACUUM).attributes["supported_features"]
    assert features & VacuumEntityFeature.START
    assert features & VacuumEntityFeature.RETURN_HOME
    assert features & VacuumEntityFeature.LOCATE
    # The hub declares no fan-speed route for this capability yet, so the
    # entity must not offer one.
    assert not features & VacuumEntityFeature.FAN_SPEED


async def test_sending_a_vacuum_home_presses_its_own_verb(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`return-to-base` is the suffix the hub's route table is keyed on."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_VACUUM)

    await hass.services.async_call(
        "vacuum", "return_to_base", {"entity_id": VACUUM}, blocking=True
    )

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(ENTITY_CHANGE_VACUUM, "vacuum_control_return_to_base")
            + "/set",
            "value": "PRESS",
        },
    )


# --- the migration ---------------------------------------------------------


async def test_the_degraded_entities_are_removed_and_the_operator_is_told(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """An entity cannot change domain in place, at any Home Assistant version.

    So the old ones are REMOVED rather than left as orphans — and the
    operator is told, because nothing else would say that
    `sensor.tapparella_salone_cover` has stopped existing until the
    automation using it failed to run.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER_LEGACY)
    registry = er.async_get(hass)
    old = registry.async_get_entity_id(
        "sensor", "camstack", "camstack_zigbee:0x0017880109_cover"
    )
    assert old is not None

    await push(hass, config_entry, ENTITY_CHANGE_COVER)

    assert (
        registry.async_get_entity_id(
            "sensor", "camstack", "camstack_zigbee:0x0017880109_cover"
        )
        is None
    )
    assert (
        registry.async_get_entity_id(
            "cover", "camstack", "camstack_zigbee:0x0017880109_cover"
        )
        is not None
    )
    assert _notifications(hass), "the operator was not told the entity id moved"


async def test_an_ordinary_removal_is_not_reported_as_a_migration(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """A device that simply stopped exporting an entity is not a migration.

    The operator is warned about entity ids that MOVED. Warning about every
    removal would train them to ignore the one that matters.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, ENTITY_CHANGE_COVER)

    shrunk = copy.deepcopy(ENTITY_CHANGE_COVER)
    del shrunk["cmps"]["sensor-battery"]
    await push(hass, config_entry, shrunk)

    assert not _notifications(hass)
