"""The rest of the native platforms.

Fan, humidifier, water heater, valve and media player.

Same rule as `test_native_platforms.py` — every fixture was generated by
the hub's own catalog, so the control names and topics asserted here are
the ones the hub actually sends.
"""

from __future__ import annotations

import copy
from typing import Any
from unittest.mock import AsyncMock

from homeassistant.components.fan import FanEntityFeature
from homeassistant.components.humidifier import HumidifierEntityFeature
from homeassistant.components.media_player import MediaPlayerEntityFeature
from homeassistant.components.valve import ValveEntityFeature
from homeassistant.components.water_heater import WaterHeaterEntityFeature
from homeassistant.core import HomeAssistant
from pytest_homeassistant_custom_component.common import MockConfigEntry

from custom_components.camstack.const import COMMAND_ROUTE_PATH

from .conftest import HEARTBEAT, load_fixture, push, setup_integration

FAN_CHANGE: dict[str, Any] = load_fixture("entity_change_fan.json")
HUMIDIFIER_CHANGE: dict[str, Any] = load_fixture("entity_change_humidifier.json")
WATER_HEATER_CHANGE: dict[str, Any] = load_fixture("entity_change_water_heater.json")
VALVE_CHANGE: dict[str, Any] = load_fixture("entity_change_valve.json")
MEDIA_CHANGE: dict[str, Any] = load_fixture("entity_change_media_player.json")

FAN = "fan.ventilatore_studio_fan_control"
HUMIDIFIER = "humidifier.umidificatore_camera_humidifier"
WATER_HEATER = "water_heater.scaldabagno_water_heater"
VALVE = "valve.valvola_giardino_valve"
MEDIA = "media_player.sonos_cucina_media_player"


def topic(message: dict[str, Any], entity: str) -> str:
    """Return the state topic the hub builds for one entity of a device."""
    return f"camstack/{message['device_id']}/{entity}"


def state_update(topic_name: str, value: str) -> dict[str, Any]:
    """Return one state update as the hub sends it — the value is a STRING."""
    return {"type": "state_update", "topic": topic_name, "value": value}


async def announce(
    hass: HomeAssistant, entry: MockConfigEntry, message: dict[str, Any]
) -> None:
    """Deliver one device and bring the link up."""
    await push(hass, entry, message)
    await push(hass, entry, HEARTBEAT)


async def command(
    hass: HomeAssistant, domain: str, service: str, data: dict[str, Any]
) -> None:
    """Call one service and settle."""
    await hass.services.async_call(domain, service, data, blocking=True)


# --- fan -------------------------------------------------------------------


async def test_a_fan_is_off_at_zero_and_not_by_a_second_value(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The capability has no on/off field: the speed IS the state.

    Deriving `is_on` from it is what stops a second value existing that
    could disagree with the first.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, FAN_CHANGE)
    await push(hass, config_entry, state_update(topic(FAN_CHANGE, "fan_control"), "0"))
    assert hass.states.get(FAN).state == "off"

    await push(hass, config_entry, state_update(topic(FAN_CHANGE, "fan_control"), "75"))
    state = hass.states.get(FAN)
    assert state.state == "on"
    assert state.attributes["percentage"] == 75


async def test_a_fan_offers_the_granularity_the_device_reported(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """A four-speed fan reports 25.

    Offering it 37 % is offering it a speed it will round to something the
    operator did not ask for, so the step comes from the DEVICE and the
    static one is only the backstop.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, FAN_CHANGE)

    assert hass.states.get(FAN).attributes["percentage_step"] == 25


async def test_a_fan_turned_off_is_speed_zero(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`fan.turn_off` writes the one field the capability has."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, FAN_CHANGE)

    await command(hass, "fan", "turn_off", {"entity_id": FAN})

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {"topic": topic(FAN_CHANGE, "fan_control") + "/set", "value": "0"},
    )


async def test_a_fan_oscillates_through_its_own_control(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Each sub-control writes the entity the route table already resolves."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, FAN_CHANGE)
    features = hass.states.get(FAN).attributes["supported_features"]
    assert features & FanEntityFeature.OSCILLATE
    assert features & FanEntityFeature.DIRECTION
    # No route for the preset, so no preset feature — the READING is still
    # there, and the entity does not offer a control that calls nothing.
    assert not features & FanEntityFeature.PRESET_MODE

    await command(hass, "fan", "oscillate", {"entity_id": FAN, "oscillating": True})

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(FAN_CHANGE, "fan_control_oscillating") + "/set",
            "value": "true",
        },
    )


# --- humidifier ------------------------------------------------------------


async def test_a_humidifier_takes_its_bounds_from_the_device(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """A unit that cannot go below 30 % must not offer 10 %."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, HUMIDIFIER_CHANGE)

    state = hass.states.get(HUMIDIFIER)
    assert state.attributes["min_humidity"] == 30
    assert state.attributes["max_humidity"] == 80


async def test_a_humidifier_reports_what_it_measures_and_what_it_is_doing(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """One entity carrying four values, which is the point of the platform."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, HUMIDIFIER_CHANGE)
    for entity, value in (
        ("humidifier", "true"),
        ("humidifier_current_humidity", "41"),
        ("humidifier_target_humidity", "55"),
        ("humidifier_action", "humidifying"),
    ):
        await push(
            hass, config_entry, state_update(topic(HUMIDIFIER_CHANGE, entity), value)
        )

    state = hass.states.get(HUMIDIFIER)
    assert state.state == "on"
    assert state.attributes["current_humidity"] == 41
    assert state.attributes["humidity"] == 55
    assert state.attributes["action"] == "humidifying"


async def test_a_humidifier_without_a_mode_route_offers_no_mode_list(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The hub routes on/off and the setpoint, and not the mode — yet."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, HUMIDIFIER_CHANGE)

    features = hass.states.get(HUMIDIFIER).attributes["supported_features"]
    assert not features & HumidifierEntityFeature.MODES


async def test_a_humidifier_sends_its_setpoint(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`humidifier.set_humidity` reaches the entity the hub routes."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, HUMIDIFIER_CHANGE)

    await command(
        hass, "humidifier", "set_humidity", {"entity_id": HUMIDIFIER, "humidity": 60}
    )

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(HUMIDIFIER_CHANGE, "humidifier_target_humidity") + "/set",
            "value": "60",
        },
    )


# --- water heater ----------------------------------------------------------


async def test_a_water_heater_state_is_its_operation_mode(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Home Assistant's water heater IS the mode, not the temperature.

    Getting this round the wrong way produces an entity whose state is
    "48.5", which no card and no automation expects.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, WATER_HEATER_CHANGE)
    await push(
        hass,
        config_entry,
        state_update(topic(WATER_HEATER_CHANGE, "water_heater_mode"), "eco"),
    )
    await push(
        hass,
        config_entry,
        state_update(topic(WATER_HEATER_CHANGE, "water_heater"), "48.5"),
    )

    state = hass.states.get(WATER_HEATER)
    assert state.state == "eco"
    assert state.attributes["current_temperature"] == 48.5
    # `operation_list` appears once the hub routes the mode: Home Assistant
    # hides the list on an entity that cannot be told to change it, which is
    # the same honesty the feature flags are for.


async def test_a_water_heater_bounds_the_setpoint_to_this_unit(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """35..65 on this tank, not the static -20..90 backstop."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, WATER_HEATER_CHANGE)

    state = hass.states.get(WATER_HEATER)
    assert state.attributes["min_temp"] == 35
    assert state.attributes["max_temp"] == 65


async def test_a_water_heater_writes_its_setpoint_and_its_away_flag(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Two controls, two entities the route table already resolves.

    The MODE has no route yet, so the entity must not advertise one.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, WATER_HEATER_CHANGE)
    features = hass.states.get(WATER_HEATER).attributes["supported_features"]
    assert features & WaterHeaterEntityFeature.TARGET_TEMPERATURE
    assert features & WaterHeaterEntityFeature.AWAY_MODE
    assert not features & WaterHeaterEntityFeature.OPERATION_MODE

    await command(
        hass,
        "water_heater",
        "set_temperature",
        {"entity_id": WATER_HEATER, "temperature": 52},
    )
    mock_client.async_post_addon_route.assert_awaited_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(WATER_HEATER_CHANGE, "water_heater_target") + "/set",
            "value": "52",
        },
    )

    await command(
        hass,
        "water_heater",
        "set_away_mode",
        {"entity_id": WATER_HEATER, "away_mode": True},
    )
    mock_client.async_post_addon_route.assert_awaited_with(
        COMMAND_ROUTE_PATH,
        {
            "topic": topic(WATER_HEATER_CHANGE, "water_heater_away") + "/set",
            "value": "true",
        },
    )


# --- valve -----------------------------------------------------------------


async def test_a_valve_that_reports_a_position_says_so(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Home Assistant asks first and treats the answer as a contract.

    A valve that claims a position and returns None for it renders as
    broken, so the answer comes from the declaration.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, VALVE_CHANGE)
    await push(hass, config_entry, state_update(topic(VALVE_CHANGE, "valve"), "open"))
    await push(
        hass, config_entry, state_update(topic(VALVE_CHANGE, "valve_position"), "60")
    )

    state = hass.states.get(VALVE)
    assert state.attributes["current_position"] == 60
    assert state.state == "open"
    assert state.attributes["supported_features"] & ValveEntityFeature.SET_POSITION


async def test_a_positionless_valve_falls_back_to_its_lifecycle(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Some valves are open or shut and nothing between."""
    message = copy.deepcopy(VALVE_CHANGE)
    del message["cmps"]["valve-valve"]["controls"]["position"]

    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, message)
    await push(hass, config_entry, state_update(topic(VALVE_CHANGE, "valve"), "closed"))

    state = hass.states.get(VALVE)
    assert state.state == "closed"
    assert not state.attributes["supported_features"] & ValveEntityFeature.SET_POSITION


async def test_closing_a_positional_valve_writes_position_zero(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Home Assistant closes a POSITIONAL valve by writing 0.

    Not this integration's choice — `ValveEntity` routes the service that
    way for anything reporting a position, which is exactly why
    `reports_position` has to be answered from the declaration.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, VALVE_CHANGE)
    await push(hass, config_entry, state_update(topic(VALVE_CHANGE, "valve"), "open"))

    await command(hass, "valve", "close_valve", {"entity_id": VALVE})

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {"topic": topic(VALVE_CHANGE, "valve_position") + "/set", "value": "0"},
    )


async def test_closing_a_positionless_valve_presses_the_verb(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """Without a position there is only the verb, and it is its own entity."""
    message = copy.deepcopy(VALVE_CHANGE)
    del message["cmps"]["valve-valve"]["controls"]["position"]

    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, message)
    await push(hass, config_entry, state_update(topic(VALVE_CHANGE, "valve"), "open"))

    await command(hass, "valve", "close_valve", {"entity_id": VALVE})

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {"topic": topic(VALVE_CHANGE, "valve_close") + "/set", "value": "PRESS"},
    )


# --- media player ----------------------------------------------------------


async def test_a_player_converts_the_volume_once_and_in_one_place(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """CamStack counts volume 0..100 and Home Assistant 0..1.

    Applying that factor on the wrong side is a player that jumps to full
    volume, so it is done here, in both directions, next to the field.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, MEDIA_CHANGE)
    await push(
        hass, config_entry, state_update(topic(MEDIA_CHANGE, "media_player"), "playing")
    )
    await push(
        hass,
        config_entry,
        state_update(topic(MEDIA_CHANGE, "media_player_volume"), "30"),
    )
    assert hass.states.get(MEDIA).attributes["volume_level"] == 0.3

    await command(
        hass, "media_player", "volume_set", {"entity_id": MEDIA, "volume_level": 0.55}
    )

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {"topic": topic(MEDIA_CHANGE, "media_player_volume") + "/set", "value": "55"},
    )


async def test_a_player_reports_transport_source_and_shuffle(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """One entity, the whole player."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, MEDIA_CHANGE)
    for entity, value in (
        ("media_player", "paused"),
        ("media_player_source", "Spotify"),
        ("media_player_shuffle", "true"),
        ("media_player_repeat", "all"),
        ("media_player_muted", "false"),
    ):
        await push(hass, config_entry, state_update(topic(MEDIA_CHANGE, entity), value))

    state = hass.states.get(MEDIA)
    assert state.state == "paused"
    assert state.attributes["source"] == "Spotify"
    assert state.attributes["shuffle"] is True
    assert state.attributes["repeat"] == "all"
    assert state.attributes["is_volume_muted"] is False


async def test_a_player_without_a_source_route_still_shows_the_source(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """The hub routes no `selectSource` yet, so it sends the reading alone.

    A read-only control is the honest shape for that, and it is why the
    reading is not thrown away with the control.
    """
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, MEDIA_CHANGE)

    features = hass.states.get(MEDIA).attributes["supported_features"]
    assert not features & MediaPlayerEntityFeature.SELECT_SOURCE
    assert features & MediaPlayerEntityFeature.VOLUME_SET
    assert features & MediaPlayerEntityFeature.PLAY
    assert features & MediaPlayerEntityFeature.NEXT_TRACK


async def test_a_transport_verb_presses_its_own_entity(
    hass: HomeAssistant, mock_client: AsyncMock, config_entry: MockConfigEntry
) -> None:
    """`media_next_track` is `media_player_next`, and nothing invented."""
    await setup_integration(hass, config_entry)
    await announce(hass, config_entry, MEDIA_CHANGE)
    await push(
        hass, config_entry, state_update(topic(MEDIA_CHANGE, "media_player"), "playing")
    )

    await command(hass, "media_player", "media_next_track", {"entity_id": MEDIA})

    mock_client.async_post_addon_route.assert_awaited_once_with(
        COMMAND_ROUTE_PATH,
        {"topic": topic(MEDIA_CHANGE, "media_player_next") + "/set", "value": "PRESS"},
    )
